/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysAdminWorkArea;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Locality.Locality;
import Business.Role.AdminRole;
import Business.State.State;
import Business.UserAccount.UserAccount;
import Business.Utils.EmailVerifier;
import Business.Utils.NumberVerifier;
import Business.Utils.StringVerifier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vega
 */
public class ManageLocalityAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageLocalityAdminJPanel
     */
    private JPanel userProcessContainer;
    private Ecosystem system;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageLocalityAdminJPanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;
addVerifiers();
        populateTable();
        populateStateComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) locjTable.getModel();

        model.setRowCount(0);
        for (State s : system.getStateList()) {
            for (Locality l : s.getLocalityDirectory().getLocalityList()) {
                for (UserAccount userAccount : l.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = l.getName();
                    row[1] = s.getStateName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
            }
        }
    }

    private void populateStateComboBox(){
       statejComboBox.removeAllItems();
        
        for (State s : system.getStateList()){
            statejComboBox.addItem(s);
        }
    }
    
    private void populateLocalityComboBox(State state){
        localityjComboBox.removeAllItems();
        
        for (Locality l : state.getLocalityDirectory().getLocalityList()){
            localityjComboBox.addItem(l);
        }
    }
       private void addVerifiers() {
        InputVerifier stringVerifier = new StringVerifier();
           InputVerifier numberVerifier = new NumberVerifier();
             InputVerifier emailVerifier = new EmailVerifier();
        userjTextField.setInputVerifier(stringVerifier);
       passjPasswordField.setInputVerifier(stringVerifier);
       namejTextField.setInputVerifier(stringVerifier);
       pNumjTextField.setInputVerifier(numberVerifier);
       mailjTextField.setInputVerifier(emailVerifier);
      }
       private Boolean checkBlankInput()
    {
        if(
                userjTextField.getText().trim().length()==0 ||
                namejTextField.getText().trim().length()==0 ||
                 passjPasswordField.getText().trim().length()==0 ||
                 pNumjTextField.getText().trim().length()==0 ||
                mailjTextField.getText().trim().length() == 0)
           
            {
                return false;
            }
        else{
            return true;
        }
    }
       private void resetFields()
        {
            userjTextField.setText("");
            passjPasswordField.setText("");
           namejTextField.setText("");
           mailjTextField.setText("");
           pNumjTextField.setText("");
            
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        locjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submitjButton = new javax.swing.JButton();
        userjTextField = new javax.swing.JTextField();
        namejTextField = new javax.swing.JTextField();
        statejComboBox = new javax.swing.JComboBox();
        localityjComboBox = new javax.swing.JComboBox();
        backjButton = new javax.swing.JButton();
        passjPasswordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        mailjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pNumjTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(231, 231, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        locjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Locality Name", "State", "User Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(locjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 580, 141));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Choose State");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Choose Locality");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("User name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, 44));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, -1, -1));

        submitjButton.setBackground(new java.awt.Color(51, 51, 255));
        submitjButton.setFont(new java.awt.Font("MT Extra", 1, 14)); // NOI18N
        submitjButton.setForeground(new java.awt.Color(255, 255, 255));
        submitjButton.setText("Submit");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });
        add(submitjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 730, 144, 39));

        userjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userjTextFieldActionPerformed(evt);
            }
        });
        add(userjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 161, -1));
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 140, -1));

        statejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statejComboBoxActionPerformed(evt);
            }
        });
        add(statejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 119, -1));

        localityjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(localityjComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 119, -1));

        backjButton.setBackground(new java.awt.Color(51, 51, 255));
        backjButton.setFont(new java.awt.Font("MT Extra", 0, 13)); // NOI18N
        backjButton.setForeground(new java.awt.Color(255, 255, 255));
        backjButton.setText("<< Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, -1, 40));
        add(passjPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 161, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, -1, -1));
        add(mailjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 140, -1));

        jLabel7.setFont(new java.awt.Font("Superclarendon", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/vega/Downloads/account-icon-10118454.jpg")); // NOI18N
        jLabel7.setText("Create Locality User Account");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 80, 620, 140));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel8.setText("Enter Details Below :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 154, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/vega/Downloads/phca_logo.png")); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Silom", 0, 10)); // NOI18N
        jLabel10.setText("National Pediatric Pneumonia Healthcare");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("Phone No :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 670, -1, -1));
        add(pNumjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 670, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userjTextFieldActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_backjButtonActionPerformed

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
  if(checkBlankInput())
  {Locality l = (Locality) localityjComboBox.getSelectedItem();
        
        String username = userjTextField.getText();
        String password = String.valueOf(passjPasswordField.getPassword());
        String name = userjTextField.getText();
        String mail = mailjTextField.getText();
        int pNumber = Integer.parseInt(pNumjTextField.getText());
        
       
        Employee employee = l.getEmployeeDirectory().createEmployee(name,mail,pNumber);
        
        UserAccount account = l.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
        
        //system.checkUsernameUnique(system, username) ;
       JOptionPane.showMessageDialog(this, "User Added", "Information", JOptionPane.INFORMATION_MESSAGE);
        
      populateTable();
        resetFields();
         }
 else
        {
            JOptionPane.showMessageDialog(this, "Please enter all values", "Error", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_submitjButtonActionPerformed

    private void statejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statejComboBoxActionPerformed
  State s = (State) statejComboBox.getSelectedItem();
        if (s != null){
            populateLocalityComboBox(s);
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_statejComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox localityjComboBox;
    private javax.swing.JTable locjTable;
    private javax.swing.JTextField mailjTextField;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JTextField pNumjTextField;
    private javax.swing.JPasswordField passjPasswordField;
    private javax.swing.JComboBox statejComboBox;
    private javax.swing.JButton submitjButton;
    private javax.swing.JTextField userjTextField;
    // End of variables declaration//GEN-END:variables
}
