/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LocalityAdmin;

import Business.Locality.Locality;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vega
 */
public class LocalityAdminJPanel extends javax.swing.JPanel {
   JPanel userProcessContainer;
   Locality locality;
    /** Creates new form AdminWorkAreaJPanel */
    public LocalityAdminJPanel(JPanel userProcessContainer, Locality locality) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.locality = locality;
        locjLabel2.setText(locality.getName());
        ljLabel.setText(locality.getName());

    }
    
    /**
     * Creates new form LocalityAdminJPanel
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEmpjButton = new javax.swing.JButton();
        manageOrgjButton = new javax.swing.JButton();
        manageUserjButton = new javax.swing.JButton();
        addHousejButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        locjLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ljLabel = new javax.swing.JLabel();
        manageHousejButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(231, 231, 253));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageEmpjButton.setBackground(new java.awt.Color(51, 51, 255));
        manageEmpjButton.setFont(new java.awt.Font("MT Extra", 1, 14)); // NOI18N
        manageEmpjButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEmpjButton.setText("Manage Employee");
        manageEmpjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmpjButtonActionPerformed(evt);
            }
        });
        add(manageEmpjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 282, 269, 59));

        manageOrgjButton.setBackground(new java.awt.Color(51, 51, 255));
        manageOrgjButton.setFont(new java.awt.Font("MT Extra", 1, 14)); // NOI18N
        manageOrgjButton.setForeground(new java.awt.Color(255, 255, 255));
        manageOrgjButton.setText("Manage Organization");
        manageOrgjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrgjButtonActionPerformed(evt);
            }
        });
        add(manageOrgjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 283, 223, 57));

        manageUserjButton.setBackground(new java.awt.Color(51, 51, 255));
        manageUserjButton.setFont(new java.awt.Font("MT Extra", 1, 14)); // NOI18N
        manageUserjButton.setForeground(new java.awt.Color(255, 255, 255));
        manageUserjButton.setText("Manage Users");
        manageUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserjButtonActionPerformed(evt);
            }
        });
        add(manageUserjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 223, 59));

        addHousejButton.setBackground(new java.awt.Color(51, 51, 255));
        addHousejButton.setFont(new java.awt.Font("MT Extra", 1, 14)); // NOI18N
        addHousejButton.setForeground(new java.awt.Color(255, 255, 255));
        addHousejButton.setText("Go >>");
        addHousejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHousejButtonActionPerformed(evt);
            }
        });
        add(addHousejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 511, 233, 59));

        jLabel1.setFont(new java.awt.Font("Superclarendon", 1, 18)); // NOI18N
        jLabel1.setText("Welcome ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 145, -1, -1));

        locjLabel2.setFont(new java.awt.Font("Superclarendon", 1, 18)); // NOI18N
        locjLabel2.setText("<value>");
        add(locjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 145, -1, -1));

        jLabel3.setBackground(new java.awt.Color(51, 51, 255));
        jLabel3.setFont(new java.awt.Font("MT Extra", 1, 18)); // NOI18N
        jLabel3.setText("Manage Houses within  ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 407, -1, -1));

        ljLabel.setBackground(new java.awt.Color(51, 51, 255));
        ljLabel.setFont(new java.awt.Font("MT Extra", 1, 18)); // NOI18N
        ljLabel.setText("<value>");
        add(ljLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 407, -1, -1));

        manageHousejButton.setBackground(new java.awt.Color(51, 51, 255));
        manageHousejButton.setFont(new java.awt.Font("MT Extra", 1, 14)); // NOI18N
        manageHousejButton.setForeground(new java.awt.Color(255, 255, 255));
        manageHousejButton.setText("Go>>");
        manageHousejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageHousejButtonActionPerformed(evt);
            }
        });
        add(manageHousejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 597, 233, 54));

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/vega/Downloads/phca_logo.png")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 6, 255, -1));

        jLabel9.setFont(new java.awt.Font("Silom", 0, 10)); // NOI18N
        jLabel9.setText("National Pediatric Pneumonia Healthcare");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 119, -1, -1));

        jLabel2.setFont(new java.awt.Font("Superclarendon", 1, 18)); // NOI18N
        jLabel2.setText("Administrator");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 145, -1, -1));

        jLabel4.setFont(new java.awt.Font("Superclarendon", 1, 14)); // NOI18N
        jLabel4.setText("Add organization ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 229, -1, -1));

        jLabel5.setFont(new java.awt.Font("Superclarendon", 1, 14)); // NOI18N
        jLabel5.setText("Add Employees ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Superclarendon", 1, 14)); // NOI18N
        jLabel6.setText("Create User Account ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setText("Add house to locality :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 529, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("Add Persons to each house :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 613, -1, -1));

        jLabel7.setFont(new java.awt.Font("Superclarendon", 1, 14)); // NOI18N
        jLabel7.setText("to your locality :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 253, -1, 17));

        jLabel12.setFont(new java.awt.Font("Superclarendon", 1, 14)); // NOI18N
        jLabel12.setText("to organization :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Superclarendon", 1, 14)); // NOI18N
        jLabel13.setText("for employee:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 130, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserjButtonActionPerformed
      ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, locality);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);   // TODO add your handling code here:
    }//GEN-LAST:event_manageUserjButtonActionPerformed

    private void manageOrgjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrgjButtonActionPerformed
ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, locality.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_manageOrgjButtonActionPerformed

    private void manageEmpjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmpjButtonActionPerformed
      ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, locality.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
           // TODO add your handling code here:
    }//GEN-LAST:event_manageEmpjButtonActionPerformed

    private void addHousejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHousejButtonActionPerformed
       AddHouseJPanel manageEmployeeJPanel = new AddHouseJPanel(userProcessContainer, locality);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); // TODO add your handling code here:*/
    }//GEN-LAST:event_addHousejButtonActionPerformed

    private void manageHousejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageHousejButtonActionPerformed
      ManageHouseJPanel manageEmployeeJPanel = new ManageHouseJPanel(userProcessContainer, locality);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);  // TODO add your handling code here:*/
    }//GEN-LAST:event_manageHousejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHousejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel ljLabel;
    private javax.swing.JLabel locjLabel2;
    private javax.swing.JButton manageEmpjButton;
    private javax.swing.JButton manageHousejButton;
    private javax.swing.JButton manageOrgjButton;
    private javax.swing.JButton manageUserjButton;
    // End of variables declaration//GEN-END:variables
}
