/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MayorAdmin;

//import static UserInterface.MayorAdmin.MayorWorkAreaJPanel.sendMail;
import Business.Employee.Employee;
import Business.Locality.Locality;
import Business.Organization.HealthCareOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vega
 */
public class ContactHealthOrgJPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
private UserAccount userAccount;
private Locality l;
    /**
     * Creates new form ContactHealthOrgJPanel
     */
    public ContactHealthOrgJPanel(JPanel userProcessContainer, UserAccount account, Locality l) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.l = l;
      populateHealthOrgComboBox();
        populateEmail();
        
    }
    public void populateEmail()
    {
       Organization org = null;
        for (Organization organization : l.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof HealthCareOrg){
                org = organization;
                break;
            }
        }
        if (org!=null){
 
    
           for (Employee e : org.getEmployeeDirectory().getEmployeeList())
           {
            String mail = e.getEmail();
           recjTextField.setText(mail);
        }
    }
    }
    public void populateHealthOrgComboBox(){
        healthcarejComboBox.removeAllItems();
        
         Organization org = null;
        for (Organization organization : l.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof HealthCareOrg){
                org = organization;
                break;
            }
        }
        if (org!=null){
 
    
           for (Employee e : org.getEmployeeDirectory().getEmployeeList())
           {
            healthcarejComboBox.addItem(e);
           
        }
    }
        
    
    }
public boolean sendMail(String from,String password,String message,String to[]){
 String host="smtp.gmail.com";
 Properties props= System.getProperties();
 props.put("mail.smtp.starttls.enable","true");
 props.put("mail.smtp.host",host );
  props.put("mail.smtp.user",from );
   props.put("mail.smtp.password",password );
    props.put("mail.smtp.port",587 );
     props.put("mail.smtp.auth","true" );
     Session session=Session.getDefaultInstance(props, null);
     MimeMessage  mimeMessage=new  MimeMessage(session);
     try{
         mimeMessage.setFrom(new InternetAddress(from));
     InternetAddress[] toAddress=new InternetAddress[to.length];
     for(int i=0;i<to.length;i++)
     {
         toAddress[i]=new InternetAddress(to[i]);
     }
     for(int i=0;i<toAddress.length;i++)
     {
     mimeMessage.addRecipient(Message.RecipientType.TO,toAddress[i]);
     
     }
     String sub = subjjTextField.getText();
     String text = composejTextField.getText();
     mimeMessage.setSubject(sub);
     mimeMessage.setText(text);
     Transport transport=session.getTransport("smtp");
     transport.connect(host,from,password);
     transport.sendMessage(mimeMessage,mimeMessage.getAllRecipients());
     transport.close();
     return false;
     }
     catch(MessagingException me)
     {
     me.printStackTrace();
     }
     
     
     
  return  false;
 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        recjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        subjjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        composejTextField = new javax.swing.JTextField();
        sendjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        healthcarejComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(231, 231, 253));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Mail Receipient");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Message Subject");

        subjjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjjTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Compose");

        sendjButton.setBackground(new java.awt.Color(51, 51, 255));
        sendjButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        sendjButton.setForeground(new java.awt.Color(255, 255, 255));
        sendjButton.setText("Send");
        sendjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Superclarendon", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/MayorAdmin/gmail.png"))); // NOI18N
        jLabel4.setText("Send Mail");

        healthcarejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        healthcarejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthcarejComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Choose Health Care Org:");

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/vega/Downloads/phca_logo.png")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Silom", 0, 10)); // NOI18N
        jLabel7.setText("National Pediatric Pneumonia Healthcare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(healthcarejComboBox, 0, 142, Short.MAX_VALUE)
                                        .addComponent(recjTextField)
                                        .addComponent(subjjTextField))
                                    .addComponent(composejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(sendjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(healthcarejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(recjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(composejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subjjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjjTextFieldActionPerformed

    private void sendjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButtonActionPerformed
String recep = recjTextField.getText();
String[] to={recep};
     if (sendMail
        ("vegashetty@gmail.com",
                "Dubstep4321",
                "Respected Madam/Sir",
                to))
     
                 JOptionPane.showMessageDialog(this, "Email status: Success", "Info", JOptionPane.INFORMATION_MESSAGE);
    
       // TODO add your handling code here:
    }//GEN-LAST:event_sendjButtonActionPerformed

    private void healthcarejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthcarejComboBoxActionPerformed
        
      populateEmail();
          // TODO add your handling code here:
    }//GEN-LAST:event_healthcarejComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField composejTextField;
    private javax.swing.JComboBox healthcarejComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField recjTextField;
    private javax.swing.JButton sendjButton;
    private javax.swing.JTextField subjjTextField;
    // End of variables declaration//GEN-END:variables
}
