/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HealthCareOrgAdmin;

import Business.Patient.Patient;
import Business.Patient.VitalSignSensor;
import Business.Patient.VitalSignSensorHistory;
import Business.Person.Person;
import Business.Utils.NumberVerifier;
import Business.Utils.StringVerifier;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vega
 */
public class CreateChildPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateChildPatientPanel
     */
    private Person person;
    private JPanel userProcessContainer;

    public CreateChildPatientPanel(JPanel upc, Person person) {
        initComponents();
        this.userProcessContainer = upc;
        this.person=person;
        addVerifiers();
        ButtonGroup();
        
        ButtonGroup1();
    }

    private void addVerifiers() {
        InputVerifier stringVerifier = new StringVerifier();
        
        InputVerifier numVerifier = new NumberVerifier();
        parentNameJTextField.setInputVerifier(stringVerifier);
        agejTextField.setInputVerifier(numVerifier);
        
    }
    private Boolean checkHstory()
    {
        if(yesjCheckBox.isSelected())
            {
                
             //nojCheckBox.setEnabled(false);
             return false;
            }
        else{
            //yesjCheckBox.setEnabled(false);
        return true;
        }
    }
     private Boolean checkInsurance()
    {
        if(YjCheckBox1.isSelected())
            {
                //NjCheckBox2.setEnabled(false);
                return false;
            }
        else{
             //YjCheckBox1.setEnabled(false);
        return true;
        }
    }
      private  void ButtonGroup()
{  ButtonGroup group = new ButtonGroup();
group.add(yesjCheckBox);
group.add(nojCheckBox);





}
       private  void ButtonGroup1()
{  ButtonGroup group1 = new ButtonGroup();


 group1.add(YjCheckBox1);
group1.add(NjCheckBox2);


}
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentNameJTextField = new javax.swing.JTextField();
        addPatientJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        patientIDJLabel = new javax.swing.JLabel();
        prefferedPharmacyJLabel = new javax.swing.JLabel();
        patientIDJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sensorjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        agejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        YjCheckBox1 = new javax.swing.JCheckBox();
        NjCheckBox2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        yesjCheckBox = new javax.swing.JCheckBox();
        nojCheckBox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(231, 231, 253));

        addPatientJButton.setBackground(new java.awt.Color(51, 51, 255));
        addPatientJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addPatientJButton.setForeground(new java.awt.Color(255, 255, 255));
        addPatientJButton.setText("Add Patient");
        addPatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Details");

        patientIDJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        patientIDJLabel.setText("Patient ID");

        prefferedPharmacyJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        prefferedPharmacyJLabel.setText("Parent name :");

        patientIDJTextField.setEditable(false);
        patientIDJTextField.setEnabled(false);

        backJButton.setBackground(new java.awt.Color(51, 51, 255));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Sensor ID");

        sensorjTextField.setEditable(false);
        sensorjTextField.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Age");

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/vega/Downloads/phca_logo.png")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Silom", 0, 10)); // NOI18N
        jLabel9.setText("National Pediatric Pneumonia Healthcare");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Insurance : ");

        YjCheckBox1.setText("Yes");
        YjCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YjCheckBox1ActionPerformed(evt);
            }
        });

        NjCheckBox2.setText("No");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Past Pneumonia History:");

        yesjCheckBox.setText("Yes");
        yesjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesjCheckBoxActionPerformed(evt);
            }
        });

        nojCheckBox.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(prefferedPharmacyJLabel)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(patientIDJLabel))
                                .addGap(195, 195, 195)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(patientIDJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(sensorjTextField)
                                        .addComponent(agejTextField))
                                    .addComponent(parentNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(YjCheckBox1)
                                        .addGap(18, 18, 18)
                                        .addComponent(NjCheckBox2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yesjCheckBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(nojCheckBox))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(addPatientJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIDJLabel)
                    .addComponent(patientIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sensorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(yesjCheckBox)
                    .addComponent(nojCheckBox))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(YjCheckBox1)
                    .addComponent(NjCheckBox2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefferedPharmacyJLabel)
                    .addComponent(parentNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(addPatientJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientJButtonActionPerformed
        // TODO add your handling code here:
        if (checkBlankInput())
        {
                               
   String yPneumonia = yesjCheckBox.getActionCommand();
 String nPneumonia = nojCheckBox.getActionCommand();
  String yInsurance = YjCheckBox1.getActionCommand();
   String nInsurance = NjCheckBox2.getActionCommand();

            Patient patient = new Patient();
            //patient.setPatientID(patientIDJTextField.getText());
            patient.setDate(new Date());
            patient.setParentName(parentNameJTextField.getText());
            patient.setAge(Integer.parseInt(agejTextField.getText()));
             if(checkHstory() == Boolean.FALSE)
             {
             patient.setPastHistory(yInsurance);
            }
             else
             {
              patient.setPastHistory(nInsurance);
             }
              if(checkInsurance()== Boolean.FALSE)
             {
             patient.setInsurance(yInsurance);
             }
             else
             {
             patient.setInsurance(nInsurance);
            }
            //Adding Patient to Person
            person.setPatient(patient);
            System.out.println("ew" + person.getPatient());
            VitalSignSensorHistory vssh = person.getPatient().getVitalSignSensorList().createAndAddSensor();
            JOptionPane.showMessageDialog(this, "Patient added!!", "Update", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
            agejTextField.setEnabled(false);
            YjCheckBox1.setEnabled(false);
            NjCheckBox2.setEnabled(false);
            yesjCheckBox.setEnabled(false);
            nojCheckBox.setEnabled(false);
            parentNameJTextField.setEnabled(false);
                    
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please enter all values", "Error", JOptionPane.ERROR_MESSAGE);
        }
        

    
        
    }//GEN-LAST:event_addPatientJButtonActionPerformed
 private void clearFields()
        {
           // patientIDJTextField.setText("");
            //sensorjTextField.setText("");
            parentNameJTextField.setText("");
            agejTextField.setText("");
        }
    private Boolean checkBlankInput()
    {
        
           if( parentNameJTextField.getText().length()==0 ||
                    agejTextField.getText().length() == 0)
            {
                return false;
            }
        else{
            return true;
        }
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);    
    }//GEN-LAST:event_backJButtonActionPerformed

    private void YjCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YjCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YjCheckBox1ActionPerformed

    private void yesjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesjCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox NjCheckBox2;
    private javax.swing.JCheckBox YjCheckBox1;
    private javax.swing.JButton addPatientJButton;
    private javax.swing.JTextField agejTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox nojCheckBox;
    private javax.swing.JTextField parentNameJTextField;
    private javax.swing.JLabel patientIDJLabel;
    private javax.swing.JTextField patientIDJTextField;
    private javax.swing.JLabel prefferedPharmacyJLabel;
    private javax.swing.JTextField sensorjTextField;
    private javax.swing.JCheckBox yesjCheckBox;
    // End of variables declaration//GEN-END:variables
}
