/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HealthCareOrgAdmin;

import Business.Patient.Patient;
import Business.Utils.StringVerifier;
import java.awt.CardLayout;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vega
 */
public class EditPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditPatientJPanel
     */
    private Patient patient;
    private JPanel userProcessContainer;
    private Boolean isEdit = Boolean.FALSE;

    public EditPatientJPanel(JPanel upc, Patient patient, Boolean isEdit) {
        initComponents();
        this.userProcessContainer = upc;
        this.patient = patient;
        this.isEdit = isEdit;
        addVerifiers();
        populatePatientDetails();
        modifyTextFields(this.isEdit);
    }

    private void addVerifiers() {
        InputVerifier stringVerifier = new StringVerifier();
        parent.setInputVerifier(stringVerifier);

    }

    private void populatePatientDetails() {
        patientIDJTextField.setText(patient.getPatientID());
        if(patient.getInsurance().equals("Yes") )
        y.setSelected(true);
        if(patient.getInsurance().equals("No") )
        n.setSelected(true);
         if(patient.getPastHistory().equals("Yes") )
        yP.setSelected(true);
          if(patient.getPastHistory().equals("No") )
        nP.setSelected(true);
          parent.setText(patient.getParentName());
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        editJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();
        patientIDJLabel = new javax.swing.JLabel();
        primaryDocNameJLabel = new javax.swing.JLabel();
        prefferedPharmacyJLabel = new javax.swing.JLabel();
        patientIDJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        parent = new javax.swing.JTextField();
        yP = new javax.swing.JCheckBox();
        nP = new javax.swing.JCheckBox();
        n = new javax.swing.JCheckBox();
        y = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(231, 231, 253));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setBackground(new java.awt.Color(51, 51, 255));
        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 565, 100, 40));

        editJButton.setBackground(new java.awt.Color(51, 51, 255));
        editJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        editJButton.setForeground(new java.awt.Color(255, 255, 255));
        editJButton.setText("Edit");
        editJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJButtonActionPerformed(evt);
            }
        });
        add(editJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 100, 30));

        saveJButton.setBackground(new java.awt.Color(51, 51, 255));
        saveJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        saveJButton.setForeground(new java.awt.Color(255, 255, 255));
        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 100, 30));

        patientIDJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        patientIDJLabel.setText("Patient ID");
        add(patientIDJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 134, -1));

        primaryDocNameJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        primaryDocNameJLabel.setText("Insurance :");
        add(primaryDocNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        prefferedPharmacyJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        prefferedPharmacyJLabel.setText("Past Pneumonia History");
        add(prefferedPharmacyJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 170, -1));
        add(patientIDJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View/Edit Patient Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 471, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/vega/Downloads/phca_logo.png")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 255, -1));

        jLabel9.setFont(new java.awt.Font("Silom", 0, 10)); // NOI18N
        jLabel9.setText("National Pediatric Pneumonia Healthcare");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Parent Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));
        add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 160, -1));

        yP.setText("Yes");
        add(yP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        nP.setText("No");
        nP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPActionPerformed(evt);
            }
        });
        add(nP, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        n.setText("No");
        add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        y.setText("Yes");
        add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void editJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJButtonActionPerformed
        // TODO add your handling code here:
        modifyTextFields(true);
    }//GEN-LAST:event_editJButtonActionPerformed
 private void modifyTextFields(Boolean isEdit) {
        if (isEdit) {
            patientIDJTextField.setEnabled(true);
            y.setEnabled(true);
             n.setEnabled(true);
             yP.setEnabled(true);
             nP.setEnabled(true);
             parent.setEnabled(true);
          
        } else {
            patientIDJTextField.setEnabled(false);
            y.setEnabled(false);
             n.setEnabled(false);
             yP.setEnabled(false);
             nP.setEnabled(false);
             parent.setEnabled(false);
            
        }
    }
  private Boolean checkBlankInput() {
        if (patientIDJTextField.getText().trim().length()==0
                || parent.getText().trim().length() == 0
                //|| prefferedPharmacyJTextField.getText().length() == 0
                ) {
            return false;
        } else {
            return true;
        }
    }
    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:

        if (checkBlankInput()) {
            patient.setPatientID(patientIDJTextField.getText());
            patient.setParentName(parent.getText());
            
            JOptionPane.showMessageDialog(this, "Patient updated!!", "Update", JOptionPane.INFORMATION_MESSAGE);
            modifyTextFields(false);
        } else {
            JOptionPane.showMessageDialog(this, "Please enter correct values", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void nPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton editJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox n;
    private javax.swing.JCheckBox nP;
    private javax.swing.JTextField parent;
    private javax.swing.JLabel patientIDJLabel;
    private javax.swing.JTextField patientIDJTextField;
    private javax.swing.JLabel prefferedPharmacyJLabel;
    private javax.swing.JLabel primaryDocNameJLabel;
    private javax.swing.JButton saveJButton;
    private javax.swing.JCheckBox y;
    private javax.swing.JCheckBox yP;
    // End of variables declaration//GEN-END:variables
}
