/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HealthCareOrgAdmin;

import Business.Locality.Locality;
import Business.Organization.HealthCareOrg;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vega
 */
public class HealthCareOrgAdminJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
   // private EmployeeDirectory employeeDirectory;
    /**
     * Creates new form ManageAccountJPanel
     */
 private HealthCareOrg healthCareOrganization;
    private Locality locality;
    private UserAccount userAccount;
    //private DonorOrganization donorOrganization;
    /**
     * Creates new form HealthCareOrgAdminJPanel
*/
    public HealthCareOrgAdminJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Locality locality) {
        initComponents();
         this.userProcessContainer= userProcessContainer;
       this.healthCareOrganization = (HealthCareOrg)organization;
       this.locality = locality;
       this.userAccount = account;
       // this.donorOrganization = (DonorOrganization)organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignToCaregiverjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        createPatientjButton = new javax.swing.JButton();
        viewjButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(231, 231, 253));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignToCaregiverjButton.setText("Assign >>");
        assignToCaregiverjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToCaregiverjButtonActionPerformed(evt);
            }
        });
        add(assignToCaregiverjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, 220, 59));

        jLabel1.setFont(new java.awt.Font("Superclarendon", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to Healthcare Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        createPatientjButton.setText("Manage >> ");
        createPatientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientjButtonActionPerformed(evt);
            }
        });
        add(createPatientjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 214, 57));

        viewjButton.setText("View >>");
        viewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewjButtonActionPerformed(evt);
            }
        });
        add(viewjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, 214, 57));

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/vega/Downloads/phca_logo.png")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 250, -1));

        jLabel9.setFont(new java.awt.Font("Silom", 0, 10)); // NOI18N
        jLabel9.setText("National Pediatric Pneumonia Healthcare");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/vega/Downloads/healthcare-insurance.jpg")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 690, -1));

        jLabel3.setFont(new java.awt.Font("Superclarendon", 1, 14)); // NOI18N
        jLabel3.setText("View Caregiver's Under Organization");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, -1, -1));

        jLabel4.setFont(new java.awt.Font("Superclarendon", 1, 14)); // NOI18N
        jLabel4.setText("Assign Patient to a Caregiver");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, -1, -1));

        jLabel5.setFont(new java.awt.Font("Superclarendon", 1, 14)); // NOI18N
        jLabel5.setText("Manage Patient Records");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignToCaregiverjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToCaregiverjButtonActionPerformed
       AssignPatientToCaregiverJPanel ms = new AssignPatientToCaregiverJPanel(userProcessContainer,userAccount,healthCareOrganization,locality);
        userProcessContainer.add("Manage", ms);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);   // TODO add your handling code here:*/
    }//GEN-LAST:event_assignToCaregiverjButtonActionPerformed

    private void createPatientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientjButtonActionPerformed
        CreatePatientJPanel cp = new CreatePatientJPanel(userProcessContainer, userAccount,healthCareOrganization,locality);
        userProcessContainer.add("ManageSupplierAdministrative", cp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_createPatientjButtonActionPerformed

    private void viewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewjButtonActionPerformed
 
        ViewCaregiversJPanel vuvsJPanel = new ViewCaregiversJPanel(userProcessContainer, locality);
        userProcessContainer.add("vuvsJPanel", vuvsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_viewjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToCaregiverjButton;
    private javax.swing.JButton createPatientjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton viewjButton;
    // End of variables declaration//GEN-END:variables
}
